# Generated by Django 5.2.5 on 2025-08-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0006_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
