# Generated by Django 5.2.5 on 2025-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0008_profile_followers_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
    model_name='profile',
    name='bio',
    field=models.TextField(blank=True, null=True, default=""),
),

    ]
