# Generated by Django 5.2.5 on 2025-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0010_remove_profile_location_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
