# Generated by Django 5.2.5 on 2025-08-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0012_remove_profile_profile_pic_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
