# Generated by Django 5.2.5 on 2025-08-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0015_remove_post_content_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='content',
        ),
    ]
