# Generated by Django 5.2.5 on 2025-08-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0016_rename_caption_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
