# Generated by Django 5.2.5 on 2025-09-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0031_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_set', to='instafinsta.profile'),
        ),
    ]
