# Generated by Django 5.2.5 on 2025-09-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0032_profile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
