# Generated by Django 5.2.5 on 2025-09-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0033_rename_author_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
    ]
