# Generated by Django on [current date]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instafinsta', '0035_remove_profile_following_alter_profile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
